### ISSUE TITLE
Trap in Room functioncalls

### ISSUE THREAD

**Issue by acdoorn** [acdoorn/cuperplusplus#7]
Kan geen functies aanroepen van Trap in Room, denk dat het te maken heeft met het aanwijzen van een ENUM aan Trap. Zal het nu oplossen door de functie in Room te maken om een trap te discoveren ipv de functie in Trap(Trap heeft dan een discoverpercentage = 80 en een dismantled = false waarde).

**Comment by jertje260** [comment]
Maak ipv een enum in de Room een Trap class die die enum heeft en de gewone functies. daarom had ik de Trap Class al gemaakt. dan kan je netjes OO blijven.
